# https://starship.rs/config/

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$python\
$docker_context\
$package\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$jobs\
$battery\
$status\
$character"""

add_newline = false

[package]
disabled = true

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[line_break]
disabled = true

[cmd_duration]
disabled = true

[[battery.display]]
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 30
style = 'bold yellow'

[git_branch]
symbol = " "

[hg_branch]
symbol = " "

[memory_usage]
symbol = " "

[python]
disabled = false
format = '[(\($virtualenv\) )]($style)'
